version: '3.3'
services:
   db:
     image: docker.io/mariadb
     volumes:
       - db_vol:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: testdb1
       MYSQL_USER: testuser
       MYSQL_PASSWORD: root
     ports:
       - 3306:3306
   web:
    build:
      context: .       
    depends_on:
      - db
    image: tomcat
    ports:
      - '8082:8080'
volumes:
    db_vol:     
